# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'interface', 'is_cat', 'classify_image']

# %% ../app.ipynb 1
from fastai.vision.all import *
import gradio as gr
def is_cat(x): return x[0].isupper()

# %% ../app.ipynb 3
learn = load_learner('model.pkl')

# %% ../app.ipynb 4
categories=('Dog','Cat')
def classify_image(img):
    pred,idx,prob=learn.predict(img)
    return dict(zip(categories,map(float,prob)))

# %% ../app.ipynb 7
image = gr.inputs.Image(shape=(192,192))
label = gr.outputs.Label()
examples=['./sample-images/blur.jpeg','./sample-images/cat.jpeg','./sample-images/cat1.jpeg','./sample-images/catdog.jpeg','./sample-images/dog.jpeg','./sample-images/cat2.jpeg','./sample-images/dog2.jpeg','./sample-images/download.jpeg','./sample-images/mix.jpeg']
interface = gr.Interface(fn=classify_image,inputs=image,outputs=label,examples=examples)
interface.launch(inline=False)
